// Curated emoji picker dataset (chat's emoji button - see _openEmojiPicker
// in Game.js). Not the full Unicode emoji spec (3000+ entries) - a
// hand-picked, commonly-used subset per category, each with a short
// space-separated keyword string ("k") the search box matches against.
// Plain Unicode characters, no image assets - renders via the OS/browser's
// own emoji font, same as any emoji already typed into chat.
export const EMOJI_CATEGORIES = [
  {
    id: 'smileys',
    labelKey: 'emojiCategorySmileys',
    icon: '😀',
    emojis: [
      { c: '😀', k: 'grin happy smile' },
      { c: '😃', k: 'happy smile joy' },
      { c: '😄', k: 'happy smile joy laugh' },
      { c: '😁', k: 'grin happy smile' },
      { c: '😆', k: 'laugh happy squint' },
      { c: '😅', k: 'sweat laugh nervous relief' },
      { c: '🤣', k: 'rofl laugh funny lol' },
      { c: '😂', k: 'laugh cry funny lol tears' },
      { c: '🙂', k: 'smile slight' },
      { c: '🙃', k: 'upside down silly' },
      { c: '😉', k: 'wink' },
      { c: '😊', k: 'smile blush happy' },
      { c: '😇', k: 'angel innocent halo' },
      { c: '🥰', k: 'love hearts adore' },
      { c: '😍', k: 'love heart eyes crush' },
      { c: '🤩', k: 'star struck excited' },
      { c: '😘', k: 'kiss love' },
      { c: '😋', k: 'yum tasty tongue' },
      { c: '😛', k: 'tongue playful' },
      { c: '😜', k: 'wink tongue silly' },
      { c: '🤪', k: 'crazy zany silly' },
      { c: '🤑', k: 'money rich greedy' },
      { c: '🤗', k: 'hug' },
      { c: '🤭', k: 'giggle oops' },
      { c: '🤫', k: 'shh quiet secret' },
      { c: '🤔', k: 'think hmm' },
      { c: '🙄', k: 'eyeroll annoyed' },
      { c: '😏', k: 'smirk sly' },
      { c: '😴', k: 'sleep tired zzz' },
      { c: '🥱', k: 'yawn tired bored' },
      { c: '😷', k: 'sick mask' },
      { c: '🤒', k: 'sick fever' },
      { c: '🤢', k: 'sick nauseous gross' },
      { c: '🤮', k: 'vomit sick gross' },
      { c: '🥵', k: 'hot sweating' },
      { c: '🥶', k: 'cold freezing' },
      { c: '😵', k: 'dizzy confused' },
      { c: '🤯', k: 'mind blown shocked' },
      { c: '🥳', k: 'party celebrate' },
      { c: '😎', k: 'cool sunglasses' },
      { c: '🥺', k: 'pleading puppy eyes' },
      { c: '😢', k: 'cry sad tear' },
      { c: '😭', k: 'sob cry sad bawling' },
      { c: '😤', k: 'huff mad frustrated' },
      { c: '😡', k: 'angry mad rage' },
      { c: '🤬', k: 'swearing furious angry' },
      { c: '💀', k: 'skull dead dying lol' },
      { c: '👻', k: 'ghost spooky' },
      { c: '🤡', k: 'clown joke' },
    ],
  },
  {
    id: 'people',
    labelKey: 'emojiCategoryPeople',
    icon: '🙌',
    emojis: [
      { c: '👋', k: 'wave hi hello bye' },
      { c: '🤚', k: 'hand stop' },
      { c: '✋', k: 'hand stop high five' },
      { c: '👌', k: 'ok okay perfect' },
      { c: '🤏', k: 'pinch small' },
      { c: '✌️', k: 'peace victory' },
      { c: '🤞', k: 'fingers crossed luck' },
      { c: '🤟', k: 'love you sign' },
      { c: '🤘', k: 'rock horns metal' },
      { c: '👍', k: 'thumbs up yes good like' },
      { c: '👎', k: 'thumbs down no bad dislike' },
      { c: '👊', k: 'fist bump punch' },
      { c: '✊', k: 'fist power' },
      { c: '👏', k: 'clap applause' },
      { c: '🙌', k: 'raised hands celebrate yay' },
      { c: '🙏', k: 'pray please thanks' },
      { c: '🤝', k: 'handshake deal' },
      { c: '💪', k: 'muscle strong flex' },
      { c: '🖕', k: 'middle finger rude' },
      { c: '✍️', k: 'writing pen' },
      { c: '👀', k: 'eyes look watching' },
      { c: '🧠', k: 'brain smart' },
      { c: '🦴', k: 'bone' },
      { c: '👤', k: 'person silhouette' },
      { c: '🧑', k: 'person' },
      { c: '👶', k: 'baby' },
      { c: '🧒', k: 'child kid' },
      { c: '👦', k: 'boy' },
      { c: '👧', k: 'girl' },
      { c: '🧔', k: 'beard man' },
      { c: '👨', k: 'man' },
      { c: '👩', k: 'woman' },
      { c: '🧓', k: 'older person elder' },
      { c: '👴', k: 'old man grandpa' },
      { c: '👵', k: 'old woman grandma' },
      { c: '🧟', k: 'zombie undead' },
      { c: '💃', k: 'dance woman' },
      { c: '🕺', k: 'dance man' },
    ],
  },
  {
    id: 'animals',
    labelKey: 'emojiCategoryAnimals',
    icon: '🐻',
    emojis: [
      { c: '🐶', k: 'dog puppy pet' },
      { c: '🐱', k: 'cat kitten pet' },
      { c: '🐭', k: 'mouse' },
      { c: '🐹', k: 'hamster' },
      { c: '🐰', k: 'rabbit bunny' },
      { c: '🦊', k: 'fox' },
      { c: '🐻', k: 'bear' },
      { c: '🐼', k: 'panda' },
      { c: '🐨', k: 'koala' },
      { c: '🐯', k: 'tiger' },
      { c: '🦁', k: 'lion' },
      { c: '🐮', k: 'cow' },
      { c: '🐷', k: 'pig' },
      { c: '🐸', k: 'frog' },
      { c: '🐵', k: 'monkey' },
      { c: '🙈', k: 'monkey see no evil' },
      { c: '🙉', k: 'monkey hear no evil' },
      { c: '🙊', k: 'monkey speak no evil' },
      { c: '🐔', k: 'chicken' },
      { c: '🐧', k: 'penguin' },
      { c: '🐦', k: 'bird' },
      { c: '🦅', k: 'eagle bird' },
      { c: '🦉', k: 'owl' },
      { c: '🦇', k: 'bat vampire' },
      { c: '🐺', k: 'wolf' },
      { c: '🐗', k: 'boar' },
      { c: '🐴', k: 'horse' },
      { c: '🦄', k: 'unicorn magic' },
      { c: '🐝', k: 'bee' },
      { c: '🐛', k: 'bug caterpillar' },
      { c: '🦋', k: 'butterfly' },
      { c: '🐌', k: 'snail slow' },
      { c: '🐞', k: 'ladybug' },
      { c: '🐢', k: 'turtle slow' },
      { c: '🐍', k: 'snake' },
      { c: '🦖', k: 'dinosaur trex' },
      { c: '🐙', k: 'octopus' },
      { c: '🦈', k: 'shark' },
      { c: '🐬', k: 'dolphin' },
      { c: '🐳', k: 'whale' },
      { c: '🐿️', k: 'squirrel' },
      { c: '🦇', k: 'bat' },
      { c: '🌵', k: 'cactus' },
      { c: '🌲', k: 'tree pine' },
      { c: '🌻', k: 'sunflower flower' },
      { c: '🌹', k: 'rose flower love' },
      { c: '🍀', k: 'clover lucky' },
    ],
  },
  {
    id: 'food',
    labelKey: 'emojiCategoryFood',
    icon: '🍔',
    emojis: [
      { c: '🍏', k: 'apple green fruit' },
      { c: '🍎', k: 'apple red fruit' },
      { c: '🍌', k: 'banana fruit' },
      { c: '🍇', k: 'grapes fruit' },
      { c: '🍓', k: 'strawberry fruit' },
      { c: '🍒', k: 'cherry fruit' },
      { c: '🍑', k: 'peach fruit' },
      { c: '🍍', k: 'pineapple fruit' },
      { c: '🥭', k: 'mango fruit' },
      { c: '🍉', k: 'watermelon fruit' },
      { c: '🍋', k: 'lemon fruit' },
      { c: '🥑', k: 'avocado' },
      { c: '🍅', k: 'tomato' },
      { c: '🌽', k: 'corn' },
      { c: '🥕', k: 'carrot' },
      { c: '🥔', k: 'potato' },
      { c: '🍞', k: 'bread' },
      { c: '🧀', k: 'cheese' },
      { c: '🍳', k: 'egg cooking fried' },
      { c: '🥓', k: 'bacon meat' },
      { c: '🍔', k: 'burger hamburger' },
      { c: '🍟', k: 'fries chips' },
      { c: '🍕', k: 'pizza' },
      { c: '🌭', k: 'hot dog' },
      { c: '🌮', k: 'taco' },
      { c: '🌯', k: 'burrito' },
      { c: '🍜', k: 'noodles ramen soup' },
      { c: '🍣', k: 'sushi' },
      { c: '🍱', k: 'bento food box' },
      { c: '🍦', k: 'ice cream soft serve' },
      { c: '🍩', k: 'donut sweet' },
      { c: '🍪', k: 'cookie sweet' },
      { c: '🎂', k: 'cake birthday' },
      { c: '🍰', k: 'cake shortcake slice' },
      { c: '🍫', k: 'chocolate' },
      { c: '🍿', k: 'popcorn movie' },
      { c: '🍺', k: 'beer drink' },
      { c: '🍻', k: 'cheers beer drink' },
      { c: '🍷', k: 'wine drink' },
      { c: '🥂', k: 'champagne cheers toast' },
      { c: '☕', k: 'coffee hot drink' },
      { c: '🧋', k: 'boba bubble tea' },
    ],
  },
  {
    id: 'activities',
    labelKey: 'emojiCategoryActivities',
    icon: '⚽',
    emojis: [
      { c: '⚽', k: 'soccer football ball' },
      { c: '🏀', k: 'basketball ball' },
      { c: '🏈', k: 'football american ball' },
      { c: '⚾', k: 'baseball ball' },
      { c: '🎾', k: 'tennis ball' },
      { c: '🏐', k: 'volleyball ball' },
      { c: '🏉', k: 'rugby ball' },
      { c: '🎱', k: 'pool billiards 8ball' },
      { c: '🏓', k: 'ping pong table tennis' },
      { c: '🏸', k: 'badminton' },
      { c: '🥊', k: 'boxing glove fight' },
      { c: '🥋', k: 'martial arts karate' },
      { c: '🎯', k: 'dart target bullseye' },
      { c: '🎮', k: 'video game controller' },
      { c: '🕹️', k: 'joystick arcade game' },
      { c: '🎲', k: 'dice game random' },
      { c: '🧩', k: 'puzzle piece' },
      { c: '🎳', k: 'bowling' },
      { c: '🏆', k: 'trophy win winner' },
      { c: '🥇', k: 'gold medal first place' },
      { c: '🥈', k: 'silver medal second' },
      { c: '🥉', k: 'bronze medal third' },
      { c: '🎖️', k: 'medal award' },
      { c: '🎨', k: 'art paint palette' },
      { c: '🎭', k: 'theater drama masks' },
      { c: '🎤', k: 'microphone sing karaoke' },
      { c: '🎧', k: 'headphones music' },
      { c: '🎸', k: 'guitar music' },
      { c: '🥁', k: 'drum music' },
      { c: '🎹', k: 'piano keyboard music' },
      { c: '🎬', k: 'movie film clapper' },
      { c: '🎪', k: 'circus tent' },
      { c: '🎉', k: 'party popper celebrate' },
      { c: '🎊', k: 'confetti party celebrate' },
      { c: '🎁', k: 'gift present' },
      { c: '🎆', k: 'fireworks' },
      { c: '🔫', k: 'gun weapon' },
      { c: '🗡️', k: 'sword dagger weapon' },
      { c: '🛡️', k: 'shield defense' },
    ],
  },
  {
    id: 'travel',
    labelKey: 'emojiCategoryTravel',
    icon: '🚗',
    emojis: [
      { c: '🚗', k: 'car vehicle' },
      { c: '🚕', k: 'taxi cab' },
      { c: '🚙', k: 'suv car vehicle' },
      { c: '🚓', k: 'police car' },
      { c: '🚑', k: 'ambulance' },
      { c: '🚒', k: 'fire truck' },
      { c: '🚚', k: 'truck delivery' },
      { c: '🏍️', k: 'motorcycle bike' },
      { c: '🚲', k: 'bicycle bike' },
      { c: '✈️', k: 'airplane plane travel' },
      { c: '🚀', k: 'rocket space launch' },
      { c: '🛸', k: 'ufo alien' },
      { c: '🚁', k: 'helicopter' },
      { c: '⛵', k: 'sailboat boat' },
      { c: '🚤', k: 'speedboat boat' },
      { c: '🚂', k: 'train locomotive' },
      { c: '🚌', k: 'bus' },
      { c: '🏠', k: 'house home' },
      { c: '🏢', k: 'building office' },
      { c: '🏥', k: 'hospital' },
      { c: '🏰', k: 'castle' },
      { c: '🗼', k: 'tower landmark' },
      { c: '🗽', k: 'statue of liberty' },
      { c: '⛰️', k: 'mountain' },
      { c: '🏔️', k: 'mountain snow' },
      { c: '🌋', k: 'volcano' },
      { c: '🏕️', k: 'camping tent' },
      { c: '🏖️', k: 'beach' },
      { c: '🏜️', k: 'desert' },
      { c: '🌃', k: 'night city stars' },
      { c: '🌆', k: 'city sunset skyline' },
      { c: '🌉', k: 'bridge night' },
      { c: '🌌', k: 'milky way stars galaxy' },
      { c: '🌍', k: 'earth globe world' },
      { c: '🌙', k: 'moon night' },
      { c: '⭐', k: 'star' },
      { c: '🌟', k: 'glowing star sparkle' },
      { c: '☀️', k: 'sun sunny' },
      { c: '⛈️', k: 'storm thunder rain' },
      { c: '🌈', k: 'rainbow' },
    ],
  },
  {
    id: 'objects',
    labelKey: 'emojiCategoryObjects',
    icon: '💡',
    emojis: [
      { c: '💡', k: 'light bulb idea' },
      { c: '🔦', k: 'flashlight torch' },
      { c: '🕯️', k: 'candle' },
      { c: '📱', k: 'phone mobile' },
      { c: '💻', k: 'laptop computer' },
      { c: '⌨️', k: 'keyboard' },
      { c: '🖥️', k: 'desktop computer monitor' },
      { c: '🖨️', k: 'printer' },
      { c: '📷', k: 'camera photo' },
      { c: '🎥', k: 'video camera film' },
      { c: '📺', k: 'tv television' },
      { c: '⏰', k: 'alarm clock time' },
      { c: '⌛', k: 'hourglass time' },
      { c: '🔋', k: 'battery' },
      { c: '🔌', k: 'plug electric' },
      { c: '🧲', k: 'magnet' },
      { c: '🔧', k: 'wrench tool' },
      { c: '🔨', k: 'hammer tool' },
      { c: '⚙️', k: 'gear settings' },
      { c: '🔗', k: 'link chain' },
      { c: '🔒', k: 'lock locked' },
      { c: '🔓', k: 'unlock unlocked' },
      { c: '🔑', k: 'key' },
      { c: '🗝️', k: 'key old' },
      { c: '💰', k: 'money bag rich' },
      { c: '💵', k: 'money cash dollar' },
      { c: '💎', k: 'gem diamond' },
      { c: '⚖️', k: 'scales balance justice' },
      { c: '🧪', k: 'test tube science' },
      { c: '🧬', k: 'dna science' },
      { c: '🔬', k: 'microscope science' },
      { c: '🔭', k: 'telescope space' },
      { c: '📡', k: 'satellite dish signal' },
      { c: '💉', k: 'syringe medicine' },
      { c: '💊', k: 'pill medicine' },
      { c: '🩹', k: 'bandage' },
      { c: '🚪', k: 'door' },
      { c: '🛏️', k: 'bed sleep' },
      { c: '🧸', k: 'teddy bear' },
      { c: '📦', k: 'box package' },
    ],
  },
  {
    id: 'symbols',
    labelKey: 'emojiCategorySymbols',
    icon: '❤️',
    emojis: [
      { c: '❤️', k: 'heart love red' },
      { c: '🧡', k: 'heart love orange' },
      { c: '💛', k: 'heart love yellow' },
      { c: '💚', k: 'heart love green' },
      { c: '💙', k: 'heart love blue' },
      { c: '💜', k: 'heart love purple' },
      { c: '🖤', k: 'heart love black' },
      { c: '🤍', k: 'heart love white' },
      { c: '🤎', k: 'heart love brown' },
      { c: '💔', k: 'broken heart sad' },
      { c: '❣️', k: 'heart exclamation love' },
      { c: '💕', k: 'two hearts love' },
      { c: '💞', k: 'revolving hearts love' },
      { c: '💓', k: 'beating heart love' },
      { c: '💗', k: 'growing heart love' },
      { c: '💖', k: 'sparkling heart love' },
      { c: '💘', k: 'cupid heart love arrow' },
      { c: '💯', k: 'hundred perfect score' },
      { c: '✅', k: 'check yes done' },
      { c: '❌', k: 'x no wrong cross' },
      { c: '❓', k: 'question mark' },
      { c: '❗', k: 'exclamation mark' },
      { c: '‼️', k: 'double exclamation' },
      { c: '⚠️', k: 'warning caution' },
      { c: '🚫', k: 'no forbidden prohibited' },
      { c: '♻️', k: 'recycle' },
      { c: '🔥', k: 'fire hot lit' },
      { c: '💥', k: 'explosion boom' },
      { c: '✨', k: 'sparkles shiny' },
      { c: '⚡', k: 'lightning bolt zap' },
      { c: '💦', k: 'sweat splash water' },
      { c: '💤', k: 'sleep zzz' },
      { c: '🆗', k: 'ok button' },
      { c: '🆕', k: 'new button' },
      { c: '🔞', k: 'no minors adult' },
      { c: '🔀', k: 'shuffle random' },
      { c: '🔁', k: 'repeat loop' },
      { c: '▶️', k: 'play button' },
      { c: '⏸️', k: 'pause button' },
      { c: '⏹️', k: 'stop button' },
    ],
  },
]
