// Stat/visual configs for each zombie archetype. Weighted random spawn mix
// lives here too so tuning difficulty is a one-file job.

export const ZOMBIE_TYPES = {
  shambler: {
    id: 'shambler',
    label: 'Shambler',
    lore: "The most common casualty of VIREO's rollout - slow, but they don't stop.",
    weight: 3,
    health: 60,
    speedMin: 1.4,
    speedMax: 2.6,
    damageMin: 35,
    damageMax: 55,
    scale: 1,
    ranged: false,
    meleeRange: 1.5,
    attackCooldown: 1.0,
    skinTones: [0x4a5539, 0x445033, 0x505a3c, 0x3d4a3f, 0x565040],
    clothesTones: [0x2a2a24, 0x27271f, 0x24241c, 0x2c2c26],
  },
  runner: {
    id: 'runner',
    label: 'Runner',
    lore: "Whatever's left of its nervous system still remembers how to sprint.",
    weight: 4,
    health: 32,
    speedMin: 4.0,
    speedMax: 5.2,
    damageMin: 25,
    damageMax: 40,
    scale: 0.9,
    ranged: false,
    meleeRange: 1.4,
    attackCooldown: 0.85,
    skinTones: [0x5c4a3a, 0x644f3d, 0x554236],
    clothesTones: [0x22201c, 0x282520],
  },
  brute: {
    id: 'brute',
    label: 'Brute',
    lore: 'Some kind of adrenal overdose. Hits like a truck.',
    weight: 2,
    health: 175,
    speedMin: 0.7,
    speedMax: 0.95,
    damageMin: 65,
    damageMax: 95,
    scale: 1.55,
    ranged: false,
    meleeRange: 2.1,
    attackCooldown: 1.4,
    skinTones: [0x3a3228, 0x342d24, 0x3d3529],
    clothesTones: [0x14120e, 0x181510],
  },
  spitter: {
    id: 'spitter',
    label: 'Spitter',
    lore: 'Keeps its distance and spits up whatever is left of its stomach lining.',
    weight: 3,
    health: 42,
    speedMin: 0.9,
    speedMax: 1.3,
    damageMin: 38,
    damageMax: 55,
    scale: 1.0,
    ranged: true,
    engageRange: 15,
    retreatRange: 7,
    spitCooldown: 2.1,
    spitTravelSpeed: 13,
    skinTones: [0x5a4a3a, 0x63533f, 0x4f4234],
    clothesTones: [0x201a14, 0x241d16],
  },
  crawler: {
    id: 'crawler',
    label: 'Crawler',
    lore: 'Lost the use of its legs. Found something faster instead.',
    weight: 3,
    health: 38,
    speedMin: 2.7,
    speedMax: 3.7,
    damageMin: 30,
    damageMax: 48,
    scale: 0.82,
    ranged: false,
    crawler: true,
    meleeRange: 1.3,
    attackCooldown: 0.8,
    skinTones: [0x4a5540, 0x424c38, 0x505c45],
    clothesTones: [0x0f1611, 0x131c15],
  },
  exploder: {
    id: 'exploder',
    label: 'Bloater',
    lore: "Don't shoot it up close. Don't shoot it at all if you can help it.",
    weight: 2,
    health: 55,
    speedMin: 1.6,
    speedMax: 2.3,
    damageMin: 0,
    damageMax: 0,
    scale: 1.2,
    ranged: false,
    explodes: true,
    meleeRange: 2.3,
    attackCooldown: 999,
    explodeRadius: 4.5,
    explodeDamageMin: 60,
    explodeDamageMax: 145,
    skinTones: [0x4a6a52, 0x4f6d55, 0x436047],
    clothesTones: [0x152018, 0x18251a],
  },
  screamer: {
    id: 'screamer',
    label: 'Screamer',
    lore: "Its scream isn't pain. It's a dinner bell.",
    weight: 2,
    health: 50,
    speedMin: 2.0,
    speedMax: 2.8,
    damageMin: 20,
    damageMax: 32,
    scale: 1.05,
    ranged: false,
    meleeRange: 1.6,
    attackCooldown: 1.1,
    // Screams on a cooldown regardless of engagement range: instantly wakes
    // every dormant (ambush) zombie in radius and briefly speeds up every
    // alive zombie in radius. See Zombie._updateScream / ZombieManager's
    // scream handling.
    screams: true,
    screamCooldown: 6.5,
    screamRadius: 15,
    screamEnrageMs: 4000,
    screamEnrageMult: 1.6,
    skinTones: [0x5c4a5e, 0x544255, 0x635066],
    clothesTones: [0x1c1620, 0x201924],
  },
  // Ranged + explode-on-death hybrid: fights like a spitter, but detonates
  // like a bloater once it dies - see Zombie.js's onHit (explodeOnDeath)
  // and _explode, which it reuses via the same explodeRadius/damage config.
  spitter_bomber: {
    id: 'spitter_bomber',
    label: 'Bomber Spitter',
    lore: "It stopped digesting a while ago. Now it just... stores things.",
    weight: 1,
    health: 48,
    speedMin: 0.9,
    speedMax: 1.3,
    damageMin: 30,
    damageMax: 45,
    scale: 1.05,
    ranged: true,
    engageRange: 14,
    retreatRange: 6,
    spitCooldown: 2.4,
    spitTravelSpeed: 12,
    explodeOnDeath: true,
    explodeRadius: 4,
    explodeDamageMin: 50,
    explodeDamageMax: 120,
    skinTones: [0x4a6a30, 0x527228, 0x466024],
    clothesTones: [0x101a08, 0x14200a],
  },
  // Screamer + summon-on-death hybrid - see ZombieManager's death handling
  // (summonOnDeath/summonType) for the shambler burst it releases.
  screamer_swarmer: {
    id: 'screamer_swarmer',
    label: 'Swarmer',
    lore: "Its scream calls them in. Its death lets them out.",
    weight: 1,
    health: 55,
    speedMin: 2.0,
    speedMax: 2.8,
    damageMin: 18,
    damageMax: 28,
    scale: 1.0,
    ranged: false,
    meleeRange: 1.5,
    attackCooldown: 1.1,
    screams: true,
    screamCooldown: 7,
    screamRadius: 14,
    screamEnrageMs: 3500,
    screamEnrageMult: 1.5,
    summonOnDeath: 2,
    summonType: 'shambler',
    skinTones: [0x6e4a5e, 0x654258, 0x724f66],
    clothesTones: [0x22141c, 0x261620],
  },
  // Boss: weight 0 means it never enters the normal random-spawn pool -
  // ZombieManager force-spawns exactly one every few nights instead.
  colossus: {
    id: 'colossus',
    label: 'Colossus',
    lore: 'Whatever they were testing scaled up. Way up.',
    weight: 0,
    health: 900,
    speedMin: 0.55,
    speedMax: 0.75,
    damageMin: 90,
    damageMax: 140,
    scale: 2.4,
    ranged: false,
    meleeRange: 2.8,
    attackCooldown: 1.8,
    skinTones: [0x1a2530, 0x16202a, 0x1c2732],
    clothesTones: [0x0a0d10, 0x0d1013],
  },
  // Second boss, alternating with colossus (see ZombieManager._spawnBoss).
  // "Feeds off light": already gets enraged for free by the flashlight's
  // light-lure mechanic (Game.js's _updateLightLure enrages any alive
  // zombie in radius) - screamEnrageMult just makes that boost hit harder
  // for this type specifically, so the light tradeoff matters most here.
  // Native to the sewer biome (see World.js's buildSewer) - just added to
  // the normal weighted pool with a small weight rather than a dedicated
  // spawn-zone system, so it can turn up anywhere, not only down there.
  sewer_dweller: {
    id: 'sewer_dweller',
    label: 'Sewer Dweller',
    lore: 'Never saw the outbreak on the surface. Never needed to.',
    weight: 1.5,
    health: 45,
    speedMin: 3.2,
    speedMax: 4.4,
    damageMin: 30,
    damageMax: 46,
    scale: 0.95,
    ranged: false,
    meleeRange: 1.4,
    attackCooldown: 0.75,
    skinTones: [0x3a4a2a, 0x334020, 0x2e3a1c],
    clothesTones: [0x141a10, 0x181f12],
  },
  patient_zero: {
    id: 'patient_zero',
    label: 'Patient Zero',
    lore: "VIREO's first success story. It feeds on the same light that made it.",
    weight: 0,
    health: 750,
    speedMin: 1.3,
    speedMax: 1.6,
    damageMin: 70,
    damageMax: 110,
    scale: 1.9,
    ranged: false,
    meleeRange: 2.4,
    attackCooldown: 1.5,
    feedsOnLight: true,
    screamEnrageMult: 2.0,
    skinTones: [0x2a0a44, 0x34104f, 0x230838],
    clothesTones: [0x0d0510, 0x120714],
  },
  // Rare roaming threat, distinct from the night-scheduled bosses above -
  // see ZombieManager's _maybeSpawnTitan, which rolls a random chance on
  // its own timer rather than a fixed night number, so it can catch the
  // player off guard mid-run instead of always being anticipated.
  titan: {
    id: 'titan',
    label: 'Titan',
    lore: "VIREO stopped documenting after this one. There's only the one entry: DO NOT REPEAT.",
    weight: 0,
    health: 1400,
    speedMin: 1.1,
    speedMax: 1.3,
    damageMin: 110,
    damageMax: 160,
    scale: 2.9,
    ranged: false,
    meleeRange: 3.0,
    attackCooldown: 1.6,
    skinTones: [0x2c1a14, 0x33201a, 0x281612],
    clothesTones: [0x0a0806, 0x0d0a08],
  },
}

export function pickZombieType() {
  const entries = Object.values(ZOMBIE_TYPES)
  const total = entries.reduce((sum, t) => sum + t.weight, 0)
  let roll = Math.random() * total
  for (const t of entries) {
    roll -= t.weight
    if (roll <= 0) return t
  }
  return entries[0]
}
